---
# tasks file for nginx
- name: "Installing Nginx on Debian Linux Flavour"
  include_tasks: ubuntu.yml
  when: ansible_os_family == Debian
- name: "Installing Nginx on RedHat Linux Flavour"
  include_tasks: centos.yml
  when: ansible_os_family == RedHat
