---
   - name: Installing java
     yum:
       name: java-1.8.0-openjdk
       state: present
       update_cache: yes
   - name: "set JAVA_HOME and JRE_HOME environment variables"
     lineinfile:
       path: /etc/environment
       line: "JAVA_HOME=/usr/lib/jvm/java-8-oracle"
       line: "JRE_HOME=/usr/lib/jvm/java-8-oracle/jre"
