---
# tasks file for java
- name : "Installing Java on Debian Family Linux Flavour"
  include_tasks: ubuntu.yml
  when:
    ansible_os_family == Debian
- name: "Installing Java on RedHat Family Linux Flavour"    
  include_tasks: centos.yml
  when:
    ansible_os_family == RedHat
